### ISSUE TITLE
Building mobile test causes go panic

### ISSUE THREAD

**Issue by borrrden** [couchbaselabs/sequoia#14]
This is the command used

```
./sequoia -test tests/mobile/test_sg.yml -scope tests/mobile/scope_1sg_1cbs.yml --expose_ports --skip_teardown --skip_test --network cbl
```

I ran it once to get rid of the noise, and this is the result of the second run (the first run also ended in the same way but with a lot more noise).  Here is the resulting output:

> →  parsed tests/mobile/scope_1sg_1cbs.yml
→  parsed tests/mobile/test_sg.yml
→  Creating network: cbl
→  parsed providers/docker/options.yml
→  start couchbase http://cbs.st:8091
[2018-07-28T08:29:56+09:00, martin/wait:75a78c] -c cbs.st:8091 -t 120
[pull] appropriate/curl
[pull] sequoiatools/couchbase-cli:5.0
[2018-07-28T08:30:15+09:00, sequoiatools/couchbase-cli:a0e7ac] node-init -c cbs.st -u Administrator -p password --node-init-data-path /opt/couchbase/var/lib/couchbase/data --node-init-index-path /opt/couchbase/var/lib/couchbase/data --node-init-analytics-path /opt/couchbase/var/lib/couchbase/data
[2018-07-28T08:30:30+09:00, sequoiatools/couchbase-cli:b2e2df] cluster-init -c cbs.st --cluster-username Administrator --cluster-password password --cluster-port 8091 --cluster-ramsize 1598 --services data
[2018-07-28T08:30:33+09:00, sequoiatools/couchbase-cli:7a8e6b] user-manage -c cbs.st -u Administrator -p password --rbac-username data-bucket --rbac-password password --roles admin --auth-domain local --set
[2018-07-28T08:30:36+09:00, sequoiatools/couchbase-cli:9dd9fb] rebalance -c cbs.st -u Administrator -p password
> ########## Cluster config ##################
> ######  kv : 1 ===== > [172.19.0.2:8091]  ###########
> [2018-07-28T08:30:42+09:00, sequoiatools/couchbase-cli:a02de0] bucket-create -c cbs.st -u Administrator -p password --bucket data-bucket --bucket-ramsize 1598 --bucket-type couchbase --bucket-replica 1 --enable-flush 1 --wait
→  parsed providers/docker/options.yml
panic: runtime error: index out of range

> goroutine 1 [running]:
github.com/couchbaselabs/sequoia/lib.BuildArgsForMobileVersion(0x0, 0x0, 0x14, 0x0, 0x3)
	/Users/borrrden/go/src/github.com/couchbaselabs/sequoia/lib/provider.go:918 +0x18a
github.com/couchbaselabs/sequoia/lib.(*DockerProvider).BuildMobileContainer(0xc4200dc900, 0xc4203522d0, 0x14e1f9f, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/borrrden/go/src/github.com/couchbaselabs/sequoia/lib/provider.go:494 +0x31b
github.com/couchbaselabs/sequoia/lib.(*DockerProvider).ProvideSyncGateways(0xc4200dc900, 0xc4201b2450, 0x1, 0x1)
	/Users/borrrden/go/src/github.com/couchbaselabs/sequoia/lib/provider.go:563 +0xac
github.com/couchbaselabs/sequoia/lib.(*Scope).SetupMobile(0xc420108dc0)
	/Users/borrrden/go/src/github.com/couchbaselabs/sequoia/lib/scope.go:144 +0x138
github.com/couchbaselabs/sequoia/lib.(*Test).Run(0xc4200ad380, 0xc4201e0000, 0x1, 0x1, 0xc4201f4000, 0x1, 0x1, 0xc4201b2450, 0x1, 0x1, ...)
	/Users/borrrden/go/src/github.com/couchbaselabs/sequoia/lib/test.go:189 +0x134
main.main()
	/Users/borrrden/go/src/github.com/couchbaselabs/sequoia/run.go:17 +0x222

**Comment by borrrden** [comment]
Oh, it's because the sync gateway version is `null` in the docker provider options...
